#pragma once

namespace Watercolor::Common {
enum ElementsIDs {
    MAIN_CANVAS = 0x99,
    MAIN_WINDOW,
    WELCOME_WINDOW,

    // Main menu
    OPEN_ABOUT_MAIN_MENU_ITEM,
    CREATE_NEW_LEVEL_MAIN_MENU_ITEM,
    OPEN_LEVEL_MAIN_MENU_ITEM,
    SAVE_LEVEL_MAIN_MENU_ITEM,
    EXIT_MAIN_MENU_ITEM,

    OPEN_LEVEL_WINDOW_LOAD_LEVEL_BUTTON,

    CURRENT_LEVEL_OBJECTS_LIST,
    SELECT_OBJECT_PROPERTY_GRID,

    // add new object items
    ADD_MESH,
    ADD_OSTREE_MESH,
    ADD_ANIMATED_MESH,
    ADD_WATER_SURFACE,
    ADD_TERRAIN_FROM_HEIGHTMAP,
    ADD_LIGHT_SOURCE,
    ADD_SKY_SPHERE,
    ADD_SKY_CUBE,
    ADD_CAMERA,
    ADD_EMPTY,
    ADD_ARROW,

    // CurrentLevelItemsTree
    ON_DRAG_LEVEL_NODE_TREE,

    // tool menu
    OPEN_VISUAL_CODE,
    PLAY_LAUNCHER,
    GIZMO_SELECT_BUTTON,
    GIZMO_MOVE_BUTTON,
    GIZMO_ROTATE_BUTTON,
    GIZMO_SCALE_BUTTON,

    // sounds editor dialog
    STOP_PLAYING_BUTTON,
    START_PLAYING_BUTTON,
    PAUSE_PLAYING_BUTTON,
    SOUNDS_LIST,

    // path builder dialog
    ENCODE_PATH_BUTTON,

    // welcome page
    OPEN_PROJECT_SITE_BUTTON,

    // GUI editor
    SELECT_GUI_ELEMENT_PROPEERTY_GRID,
    GUI_EDITOR_CANVAS,
    VIEWS_LIST,
    DRAW_GRID_CHECKBOX,
    USE_GRID_CHECKBOX,
    ADD_WINDOW,
    ADD_BUTTON,
    ADD_IMAGE,
    ADD_LABLE,
    ADD_TEXTBOX,
    ADD_CHECKBOX,
    ADD_LISTBOX,
    ADD_VIEW,
    REMOVE_VIEW,
    GUI_EDITOR_ADD_VIEW,
    GUI_EDITOR_SAVE_VIEW,
    GUI_EDITOR_OPEN_VIEW,
    GUI_EDITOR_REMOVE_VIEW,

    // Game builder
    GAME_BUILDER_BUILD_BUTTON,

    // Welcome screen
    WELCOME_SCREEN_LOAD_RECENTLY_PROJECT,
    WELCOME_SCREEN_LOAD_PROJECT,
    FIRST_FREE
};
}